/*
 * WARNING: this file has been generated by
 * Hime Parser Generator 3.4.0.0
 */
using System.Collections.Generic;
using System.IO;
using Hime.Redist;
using Hime.Redist.Lexer;

namespace Express
{
	/// <summary>
	/// Represents a lexer
	/// </summary>
	internal class ExpressLexer : ContextFreeLexer
	{
		/// <summary>
		/// The automaton for this lexer
		/// </summary>
		private static readonly Automaton commonAutomaton = Automaton.Find(typeof(ExpressLexer), "ExpressLexer.bin");
		/// <summary>
		/// Contains the constant IDs for the terminals for this lexer
		/// </summary>
		public class ID
		{
			/// <summary>
			/// The unique identifier for terminal NEW_LINE
			/// </summary>
			public const int TerminalNewLine = 0x0003;
			/// <summary>
			/// The unique identifier for terminal WHITE_SPACE
			/// </summary>
			public const int TerminalWhiteSpace = 0x0004;
			/// <summary>
			/// The unique identifier for terminal SEPARATOR
			/// </summary>
			public const int TerminalSeparator = 0x0005;
			/// <summary>
			/// The unique identifier for terminal IDENTIFIER
			/// </summary>
			public const int TerminalIdentifier = 0x0006;
			/// <summary>
			/// The unique identifier for terminal ANNOTATION
			/// </summary>
			public const int TerminalAnnotation = 0x0007;
			/// <summary>
			/// The unique identifier for terminal INLINE_ANNOTATION
			/// </summary>
			public const int TerminalInlineAnnotation = 0x0008;
			/// <summary>
			/// The unique identifier for terminal INTEGER_LITERAL_DECIMAL
			/// </summary>
			public const int TerminalIntegerLiteralDecimal = 0x0009;
			/// <summary>
			/// The unique identifier for terminal INTEGER_LITERAL_HEXA
			/// </summary>
			public const int TerminalIntegerLiteralHexa = 0x000A;
			/// <summary>
			/// The unique identifier for terminal REAL_LITERAL
			/// </summary>
			public const int TerminalRealLiteral = 0x000B;
			/// <summary>
			/// The unique identifier for terminal STRING_LITERAL
			/// </summary>
			public const int TerminalStringLiteral = 0x000C;
		}
		/// <summary>
		/// Contains the constant IDs for the contexts for this lexer
		/// </summary>
		public class Context
		{
			/// <summary>
			/// The unique identifier for the default context
			/// </summary>
			public const int Default = 0;
		}
		/// <summary>
		/// The collection of terminals matched by this lexer
		/// </summary>
		/// <remarks>
		/// The terminals are in an order consistent with the automaton,
		/// so that terminal indices in the automaton can be used to retrieve the terminals in this table
		/// </remarks>
		private static readonly Symbol[] terminals = {
			new Symbol(0x0001, "ε"),
			new Symbol(0x0002, "$"),
			new Symbol(0x0003, "NEW_LINE"),
			new Symbol(0x0004, "WHITE_SPACE"),
			new Symbol(0x0005, "SEPARATOR"),
			new Symbol(0x0006, "IDENTIFIER"),
			new Symbol(0x0007, "ANNOTATION"),
			new Symbol(0x0008, "INLINE_ANNOTATION"),
			new Symbol(0x0009, "INTEGER_LITERAL_DECIMAL"),
			new Symbol(0x000A, "INTEGER_LITERAL_HEXA"),
			new Symbol(0x000B, "REAL_LITERAL"),
			new Symbol(0x000C, "STRING_LITERAL"),
			new Symbol(0x0045, "USE"),
			new Symbol(0x0046, "FROM"),
			new Symbol(0x0047, ";"),
			new Symbol(0x0048, "SCHEMA"),
			new Symbol(0x0049, "TYPE"),
			new Symbol(0x004A, "="),
			new Symbol(0x004B, "END_TYPE"),
			new Symbol(0x004C, "SELECT"),
			new Symbol(0x004D, "("),
			new Symbol(0x004E, ","),
			new Symbol(0x0050, ")"),
			new Symbol(0x0051, "ENTITY"),
			new Symbol(0x0053, "END_ENTITY"),
			new Symbol(0x0054, "ENUMERATION"),
			new Symbol(0x0055, "OF"),
			new Symbol(0x0057, "ABSTRACT"),
			new Symbol(0x0058, "SUBTYPE"),
			new Symbol(0x005A, "SUPERTYPE"),
			new Symbol(0x005B, "DERIVE"),
			new Symbol(0x005D, ":"),
			new Symbol(0x005E, ":="),
			new Symbol(0x005F, "UNIQUE"),
			new Symbol(0x0062, "SELF"),
			new Symbol(0x0063, "SELF\\"),
			new Symbol(0x0064, "\\"),
			new Symbol(0x0065, "."),
			new Symbol(0x0067, "["),
			new Symbol(0x0068, "]"),
			new Symbol(0x0069, "LIST"),
			new Symbol(0x006A, "*"),
			new Symbol(0x006D, "SET"),
			new Symbol(0x006E, "QUERY"),
			new Symbol(0x006F, "|"),
			new Symbol(0x0070, "?"),
			new Symbol(0x0071, "OPTIONAL"),
			new Symbol(0x0072, "WHERE"),
			new Symbol(0x0074, "OR"),
			new Symbol(0x0075, "AND"),
			new Symbol(0x0076, "NOT"),
			new Symbol(0x0077, "EXISTS"),
			new Symbol(0x0078, "{"),
			new Symbol(0x0079, "}"),
			new Symbol(0x007A, "TYPEOF"),
			new Symbol(0x007B, "USEDIN"),
			new Symbol(0x007D, "SIZEOF"),
			new Symbol(0x007E, ":<>:"),
			new Symbol(0x007F, ":=:"),
			new Symbol(0x0080, "IN"),
			new Symbol(0x0081, "<"),
			new Symbol(0x0082, "<="),
			new Symbol(0x0083, "<*"),
			new Symbol(0x0084, ">="),
			new Symbol(0x0085, ">"),
			new Symbol(0x0086, ">*"),
			new Symbol(0x0087, "ONEOF"),
			new Symbol(0x0089, "STRING"),
			new Symbol(0x008A, "NUMBER"),
			new Symbol(0x008B, "BOOLEAN"),
			new Symbol(0x008C, "LOGICAL"),
			new Symbol(0x008D, "BINARY"),
			new Symbol(0x008E, "INTEGER"),
			new Symbol(0x008F, "REAL"),
			new Symbol(0x0090, "true"),
			new Symbol(0x0091, "false") };
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public ExpressLexer(string input) : base(commonAutomaton, terminals, 0x0005, input) {}
		/// <summary>
		/// Initializes a new instance of the lexer
		/// </summary>
		/// <param name="input">The lexer's input</param>
		public ExpressLexer(TextReader input) : base(commonAutomaton, terminals, 0x0005, input) {}
	}
}
